### ISSUE TITLE
[todo] change layout

### ISSUE THREAD

**Issue by hjyssg** [hjyssg/python-web-pdb#1]
util.js 

```js
function resize_console() {
  let con_height = $(window).height() - 490;
  if (con_height <= 240) {
    con_height = 240;
  }

  con_height  = math.min(con_height, 500);
  $('#console').height(con_height);
}

```

**Comment by hjyssg** [comment]
```css
.code-info {
    height: 1000px;
}
```
